import type { NextPage } from "next";
import {
  useAuthUser,
  withAuthUser,
  withAuthUserTokenSSR,
  AuthAction,
} from "next-firebase-auth";
import Link from "next/link";
import Head from "next/head";
import login from "../utils/login";

const Home: NextPage = () => {
  const AuthUser = useAuthUser();
  return (
    <div>
      <Head>
        <title>Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          {AuthUser.email ? (
            <div>
              <p>logged in + ratio + {AuthUser.email}</p>
              <button onClick={() => AuthUser.signOut()}>signout</button>
            </div>
          ) : (
            <div>
              <p>not logged in</p>
              <button onClick={() => login()}>Login</button>
            </div>
          )}
        </div>
      </main>
    </div>
  );
};

const MyLoader = () => <div>Loading...</div>;

export default withAuthUser({
  whenUnauthedBeforeInit: AuthAction.SHOW_LOADER,
  LoaderComponent: MyLoader,
})(Home);
